#!/usr/bin/perl -w

# Generate usys.S, the stubs for syscalls.

print "# generated by usys.pl - do not edit\n";

print "#include \"kernel/syscall.h\"\n";

sub entry {
    my $name = shift;
    print ".global $name\n";
    print "${name}:\n";
    print " li a7, SYS_${name}\n";
    print " ecall\n";
    print " ret\n";
}
	
entry("fork");
entry("exit");
entry("wait");
entry("pipe");
entry("read");
entry("write");
entry("close");
entry("kill");
entry("exec");
entry("open");
entry("mknod");
entry("unlink");
entry("fstat");
entry("link");
entry("mkdir");
entry("chdir");
entry("dup");
entry("getpid");
entry("sbrk");
entry("sleep");
entry("uptime");

entry("sigprocmask");   # Task 2.1.3
entry("sigaction");     # Task 2.1.4
entry("sigret");        # Task 2.1.5

entry("kthread_create");    # Task 3.2
entry("kthread_id");        # Task 3.2
entry("kthread_exit");      # Task 3.2 
entry("kthread_join");      # Task 3.2 

entry("bsem_alloc");    # Task 4.1
entry("bsem_free");     # Task 4.1
entry("bsem_up");       # Task 4.1
entry("bsem_down");     # Task 4.1
